// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: couchbase/admin/query/v1/query.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Couchbase.Protostellar.Admin.Query.V1 {
  public static partial class QueryAdminService
  {
    static readonly string __ServiceName = "couchbase.admin.query.v1.QueryAdminService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesRequest> __Marshaller_couchbase_admin_query_v1_GetAllIndexesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesResponse> __Marshaller_couchbase_admin_query_v1_GetAllIndexesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexRequest> __Marshaller_couchbase_admin_query_v1_CreatePrimaryIndexRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexResponse> __Marshaller_couchbase_admin_query_v1_CreatePrimaryIndexResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexRequest> __Marshaller_couchbase_admin_query_v1_CreateIndexRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexResponse> __Marshaller_couchbase_admin_query_v1_CreateIndexResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexRequest> __Marshaller_couchbase_admin_query_v1_DropPrimaryIndexRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexResponse> __Marshaller_couchbase_admin_query_v1_DropPrimaryIndexResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Query.V1.DropIndexRequest> __Marshaller_couchbase_admin_query_v1_DropIndexRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Query.V1.DropIndexRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Query.V1.DropIndexResponse> __Marshaller_couchbase_admin_query_v1_DropIndexResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Query.V1.DropIndexResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesRequest> __Marshaller_couchbase_admin_query_v1_BuildDeferredIndexesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesResponse> __Marshaller_couchbase_admin_query_v1_BuildDeferredIndexesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesRequest, global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesResponse> __Method_GetAllIndexes = new grpc::Method<global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesRequest, global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllIndexes",
        __Marshaller_couchbase_admin_query_v1_GetAllIndexesRequest,
        __Marshaller_couchbase_admin_query_v1_GetAllIndexesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexRequest, global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexResponse> __Method_CreatePrimaryIndex = new grpc::Method<global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexRequest, global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreatePrimaryIndex",
        __Marshaller_couchbase_admin_query_v1_CreatePrimaryIndexRequest,
        __Marshaller_couchbase_admin_query_v1_CreatePrimaryIndexResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexRequest, global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexResponse> __Method_CreateIndex = new grpc::Method<global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexRequest, global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateIndex",
        __Marshaller_couchbase_admin_query_v1_CreateIndexRequest,
        __Marshaller_couchbase_admin_query_v1_CreateIndexResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexRequest, global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexResponse> __Method_DropPrimaryIndex = new grpc::Method<global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexRequest, global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DropPrimaryIndex",
        __Marshaller_couchbase_admin_query_v1_DropPrimaryIndexRequest,
        __Marshaller_couchbase_admin_query_v1_DropPrimaryIndexResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Admin.Query.V1.DropIndexRequest, global::Couchbase.Protostellar.Admin.Query.V1.DropIndexResponse> __Method_DropIndex = new grpc::Method<global::Couchbase.Protostellar.Admin.Query.V1.DropIndexRequest, global::Couchbase.Protostellar.Admin.Query.V1.DropIndexResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DropIndex",
        __Marshaller_couchbase_admin_query_v1_DropIndexRequest,
        __Marshaller_couchbase_admin_query_v1_DropIndexResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesRequest, global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesResponse> __Method_BuildDeferredIndexes = new grpc::Method<global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesRequest, global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BuildDeferredIndexes",
        __Marshaller_couchbase_admin_query_v1_BuildDeferredIndexesRequest,
        __Marshaller_couchbase_admin_query_v1_BuildDeferredIndexesResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Couchbase.Protostellar.Admin.Query.V1.QueryReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for QueryAdminService</summary>
    public partial class QueryAdminServiceClient : grpc::ClientBase<QueryAdminServiceClient>
    {
      /// <summary>Creates a new client for QueryAdminService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public QueryAdminServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for QueryAdminService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public QueryAdminServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected QueryAdminServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected QueryAdminServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesResponse GetAllIndexes(global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllIndexes(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesResponse GetAllIndexes(global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllIndexes, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesResponse> GetAllIndexesAsync(global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllIndexesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesResponse> GetAllIndexesAsync(global::Couchbase.Protostellar.Admin.Query.V1.GetAllIndexesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllIndexes, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexResponse CreatePrimaryIndex(global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreatePrimaryIndex(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexResponse CreatePrimaryIndex(global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreatePrimaryIndex, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexResponse> CreatePrimaryIndexAsync(global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreatePrimaryIndexAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexResponse> CreatePrimaryIndexAsync(global::Couchbase.Protostellar.Admin.Query.V1.CreatePrimaryIndexRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreatePrimaryIndex, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexResponse CreateIndex(global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateIndex(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexResponse CreateIndex(global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateIndex, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexResponse> CreateIndexAsync(global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateIndexAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexResponse> CreateIndexAsync(global::Couchbase.Protostellar.Admin.Query.V1.CreateIndexRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateIndex, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexResponse DropPrimaryIndex(global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DropPrimaryIndex(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexResponse DropPrimaryIndex(global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DropPrimaryIndex, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexResponse> DropPrimaryIndexAsync(global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DropPrimaryIndexAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexResponse> DropPrimaryIndexAsync(global::Couchbase.Protostellar.Admin.Query.V1.DropPrimaryIndexRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DropPrimaryIndex, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Query.V1.DropIndexResponse DropIndex(global::Couchbase.Protostellar.Admin.Query.V1.DropIndexRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DropIndex(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Query.V1.DropIndexResponse DropIndex(global::Couchbase.Protostellar.Admin.Query.V1.DropIndexRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DropIndex, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Query.V1.DropIndexResponse> DropIndexAsync(global::Couchbase.Protostellar.Admin.Query.V1.DropIndexRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DropIndexAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Query.V1.DropIndexResponse> DropIndexAsync(global::Couchbase.Protostellar.Admin.Query.V1.DropIndexRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DropIndex, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesResponse BuildDeferredIndexes(global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BuildDeferredIndexes(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesResponse BuildDeferredIndexes(global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_BuildDeferredIndexes, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesResponse> BuildDeferredIndexesAsync(global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BuildDeferredIndexesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesResponse> BuildDeferredIndexesAsync(global::Couchbase.Protostellar.Admin.Query.V1.BuildDeferredIndexesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_BuildDeferredIndexes, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override QueryAdminServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new QueryAdminServiceClient(configuration);
      }
    }

  }
}
#endregion
