// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: couchbase/transactions/v1/transactions.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Couchbase.Protostellar.Transactions.V1 {
  public static partial class TransactionsService
  {
    static readonly string __ServiceName = "couchbase.transactions.v1.TransactionsService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptRequest> __Marshaller_couchbase_transactions_v1_TransactionBeginAttemptRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptResponse> __Marshaller_couchbase_transactions_v1_TransactionBeginAttemptResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Transactions.V1.TransactionCommitRequest> __Marshaller_couchbase_transactions_v1_TransactionCommitRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Transactions.V1.TransactionCommitRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Transactions.V1.TransactionCommitResponse> __Marshaller_couchbase_transactions_v1_TransactionCommitResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Transactions.V1.TransactionCommitResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackRequest> __Marshaller_couchbase_transactions_v1_TransactionRollbackRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackResponse> __Marshaller_couchbase_transactions_v1_TransactionRollbackResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Transactions.V1.TransactionGetRequest> __Marshaller_couchbase_transactions_v1_TransactionGetRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Transactions.V1.TransactionGetRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Transactions.V1.TransactionGetResponse> __Marshaller_couchbase_transactions_v1_TransactionGetResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Transactions.V1.TransactionGetResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Transactions.V1.TransactionInsertRequest> __Marshaller_couchbase_transactions_v1_TransactionInsertRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Transactions.V1.TransactionInsertRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Transactions.V1.TransactionInsertResponse> __Marshaller_couchbase_transactions_v1_TransactionInsertResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Transactions.V1.TransactionInsertResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceRequest> __Marshaller_couchbase_transactions_v1_TransactionReplaceRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceResponse> __Marshaller_couchbase_transactions_v1_TransactionReplaceResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveRequest> __Marshaller_couchbase_transactions_v1_TransactionRemoveRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveResponse> __Marshaller_couchbase_transactions_v1_TransactionRemoveResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptRequest, global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptResponse> __Method_TransactionBeginAttempt = new grpc::Method<global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptRequest, global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TransactionBeginAttempt",
        __Marshaller_couchbase_transactions_v1_TransactionBeginAttemptRequest,
        __Marshaller_couchbase_transactions_v1_TransactionBeginAttemptResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Transactions.V1.TransactionCommitRequest, global::Couchbase.Protostellar.Transactions.V1.TransactionCommitResponse> __Method_TransactionCommit = new grpc::Method<global::Couchbase.Protostellar.Transactions.V1.TransactionCommitRequest, global::Couchbase.Protostellar.Transactions.V1.TransactionCommitResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TransactionCommit",
        __Marshaller_couchbase_transactions_v1_TransactionCommitRequest,
        __Marshaller_couchbase_transactions_v1_TransactionCommitResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackRequest, global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackResponse> __Method_TransactionRollback = new grpc::Method<global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackRequest, global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TransactionRollback",
        __Marshaller_couchbase_transactions_v1_TransactionRollbackRequest,
        __Marshaller_couchbase_transactions_v1_TransactionRollbackResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Transactions.V1.TransactionGetRequest, global::Couchbase.Protostellar.Transactions.V1.TransactionGetResponse> __Method_TransactionGet = new grpc::Method<global::Couchbase.Protostellar.Transactions.V1.TransactionGetRequest, global::Couchbase.Protostellar.Transactions.V1.TransactionGetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TransactionGet",
        __Marshaller_couchbase_transactions_v1_TransactionGetRequest,
        __Marshaller_couchbase_transactions_v1_TransactionGetResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Transactions.V1.TransactionInsertRequest, global::Couchbase.Protostellar.Transactions.V1.TransactionInsertResponse> __Method_TransactionInsert = new grpc::Method<global::Couchbase.Protostellar.Transactions.V1.TransactionInsertRequest, global::Couchbase.Protostellar.Transactions.V1.TransactionInsertResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TransactionInsert",
        __Marshaller_couchbase_transactions_v1_TransactionInsertRequest,
        __Marshaller_couchbase_transactions_v1_TransactionInsertResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceRequest, global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceResponse> __Method_TransactionReplace = new grpc::Method<global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceRequest, global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TransactionReplace",
        __Marshaller_couchbase_transactions_v1_TransactionReplaceRequest,
        __Marshaller_couchbase_transactions_v1_TransactionReplaceResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveRequest, global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveResponse> __Method_TransactionRemove = new grpc::Method<global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveRequest, global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TransactionRemove",
        __Marshaller_couchbase_transactions_v1_TransactionRemoveRequest,
        __Marshaller_couchbase_transactions_v1_TransactionRemoveResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Couchbase.Protostellar.Transactions.V1.TransactionsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for TransactionsService</summary>
    public partial class TransactionsServiceClient : grpc::ClientBase<TransactionsServiceClient>
    {
      /// <summary>Creates a new client for TransactionsService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public TransactionsServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TransactionsService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public TransactionsServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected TransactionsServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected TransactionsServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptResponse TransactionBeginAttempt(global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransactionBeginAttempt(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptResponse TransactionBeginAttempt(global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TransactionBeginAttempt, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptResponse> TransactionBeginAttemptAsync(global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransactionBeginAttemptAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptResponse> TransactionBeginAttemptAsync(global::Couchbase.Protostellar.Transactions.V1.TransactionBeginAttemptRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TransactionBeginAttempt, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Transactions.V1.TransactionCommitResponse TransactionCommit(global::Couchbase.Protostellar.Transactions.V1.TransactionCommitRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransactionCommit(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Transactions.V1.TransactionCommitResponse TransactionCommit(global::Couchbase.Protostellar.Transactions.V1.TransactionCommitRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TransactionCommit, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Transactions.V1.TransactionCommitResponse> TransactionCommitAsync(global::Couchbase.Protostellar.Transactions.V1.TransactionCommitRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransactionCommitAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Transactions.V1.TransactionCommitResponse> TransactionCommitAsync(global::Couchbase.Protostellar.Transactions.V1.TransactionCommitRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TransactionCommit, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackResponse TransactionRollback(global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransactionRollback(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackResponse TransactionRollback(global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TransactionRollback, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackResponse> TransactionRollbackAsync(global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransactionRollbackAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackResponse> TransactionRollbackAsync(global::Couchbase.Protostellar.Transactions.V1.TransactionRollbackRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TransactionRollback, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Transactions.V1.TransactionGetResponse TransactionGet(global::Couchbase.Protostellar.Transactions.V1.TransactionGetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransactionGet(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Transactions.V1.TransactionGetResponse TransactionGet(global::Couchbase.Protostellar.Transactions.V1.TransactionGetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TransactionGet, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Transactions.V1.TransactionGetResponse> TransactionGetAsync(global::Couchbase.Protostellar.Transactions.V1.TransactionGetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransactionGetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Transactions.V1.TransactionGetResponse> TransactionGetAsync(global::Couchbase.Protostellar.Transactions.V1.TransactionGetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TransactionGet, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Transactions.V1.TransactionInsertResponse TransactionInsert(global::Couchbase.Protostellar.Transactions.V1.TransactionInsertRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransactionInsert(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Transactions.V1.TransactionInsertResponse TransactionInsert(global::Couchbase.Protostellar.Transactions.V1.TransactionInsertRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TransactionInsert, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Transactions.V1.TransactionInsertResponse> TransactionInsertAsync(global::Couchbase.Protostellar.Transactions.V1.TransactionInsertRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransactionInsertAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Transactions.V1.TransactionInsertResponse> TransactionInsertAsync(global::Couchbase.Protostellar.Transactions.V1.TransactionInsertRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TransactionInsert, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceResponse TransactionReplace(global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransactionReplace(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceResponse TransactionReplace(global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TransactionReplace, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceResponse> TransactionReplaceAsync(global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransactionReplaceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceResponse> TransactionReplaceAsync(global::Couchbase.Protostellar.Transactions.V1.TransactionReplaceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TransactionReplace, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveResponse TransactionRemove(global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransactionRemove(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveResponse TransactionRemove(global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TransactionRemove, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveResponse> TransactionRemoveAsync(global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransactionRemoveAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveResponse> TransactionRemoveAsync(global::Couchbase.Protostellar.Transactions.V1.TransactionRemoveRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TransactionRemove, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override TransactionsServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TransactionsServiceClient(configuration);
      }
    }

  }
}
#endregion
