
using Newtonsoft.Json;

namespace Couchbase.N1QL
{
    public class QueryPlan
    {
        /// <summary>
        /// Gets the name of the query plan generated by the server.
        /// </summary>
        /// <value>
        /// The name of the query plan.
        /// </value>
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("signature")]
        public object Signature { get; set; }

        [JsonProperty("encoded_plan")]
        public string EncodedPlan { get; set; }

        [JsonProperty("operator")]
        public object Operator { get; set; }
    }
}