// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: couchbase/admin/bucket/v1/bucket.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Couchbase.Protostellar.Admin.Bucket.V1 {
  public static partial class BucketAdminService
  {
    static readonly string __ServiceName = "couchbase.admin.bucket.v1.BucketAdminService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsRequest> __Marshaller_couchbase_admin_bucket_v1_ListBucketsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsResponse> __Marshaller_couchbase_admin_bucket_v1_ListBucketsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketRequest> __Marshaller_couchbase_admin_bucket_v1_CreateBucketRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketResponse> __Marshaller_couchbase_admin_bucket_v1_CreateBucketResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketRequest> __Marshaller_couchbase_admin_bucket_v1_UpdateBucketRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketResponse> __Marshaller_couchbase_admin_bucket_v1_UpdateBucketResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketRequest> __Marshaller_couchbase_admin_bucket_v1_DeleteBucketRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketResponse> __Marshaller_couchbase_admin_bucket_v1_DeleteBucketResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsRequest, global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsResponse> __Method_ListBuckets = new grpc::Method<global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsRequest, global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListBuckets",
        __Marshaller_couchbase_admin_bucket_v1_ListBucketsRequest,
        __Marshaller_couchbase_admin_bucket_v1_ListBucketsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketRequest, global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketResponse> __Method_CreateBucket = new grpc::Method<global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketRequest, global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateBucket",
        __Marshaller_couchbase_admin_bucket_v1_CreateBucketRequest,
        __Marshaller_couchbase_admin_bucket_v1_CreateBucketResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketRequest, global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketResponse> __Method_UpdateBucket = new grpc::Method<global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketRequest, global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateBucket",
        __Marshaller_couchbase_admin_bucket_v1_UpdateBucketRequest,
        __Marshaller_couchbase_admin_bucket_v1_UpdateBucketResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketRequest, global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketResponse> __Method_DeleteBucket = new grpc::Method<global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketRequest, global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteBucket",
        __Marshaller_couchbase_admin_bucket_v1_DeleteBucketRequest,
        __Marshaller_couchbase_admin_bucket_v1_DeleteBucketResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Couchbase.Protostellar.Admin.Bucket.V1.BucketReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for BucketAdminService</summary>
    public partial class BucketAdminServiceClient : grpc::ClientBase<BucketAdminServiceClient>
    {
      /// <summary>Creates a new client for BucketAdminService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public BucketAdminServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for BucketAdminService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public BucketAdminServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected BucketAdminServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected BucketAdminServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsResponse ListBuckets(global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListBuckets(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsResponse ListBuckets(global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListBuckets, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsResponse> ListBucketsAsync(global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListBucketsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsResponse> ListBucketsAsync(global::Couchbase.Protostellar.Admin.Bucket.V1.ListBucketsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListBuckets, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketResponse CreateBucket(global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateBucket(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketResponse CreateBucket(global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateBucket, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketResponse> CreateBucketAsync(global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateBucketAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketResponse> CreateBucketAsync(global::Couchbase.Protostellar.Admin.Bucket.V1.CreateBucketRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateBucket, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketResponse UpdateBucket(global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateBucket(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketResponse UpdateBucket(global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateBucket, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketResponse> UpdateBucketAsync(global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateBucketAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketResponse> UpdateBucketAsync(global::Couchbase.Protostellar.Admin.Bucket.V1.UpdateBucketRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateBucket, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketResponse DeleteBucket(global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteBucket(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketResponse DeleteBucket(global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteBucket, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketResponse> DeleteBucketAsync(global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteBucketAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketResponse> DeleteBucketAsync(global::Couchbase.Protostellar.Admin.Bucket.V1.DeleteBucketRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteBucket, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override BucketAdminServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BucketAdminServiceClient(configuration);
      }
    }

  }
}
#endregion
