// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: couchbase/kv/v1/kv.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Couchbase.Protostellar.KV.V1 {
  public static partial class KvService
  {
    static readonly string __ServiceName = "couchbase.kv.v1.KvService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.GetRequest> __Marshaller_couchbase_kv_v1_GetRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.GetRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.GetResponse> __Marshaller_couchbase_kv_v1_GetResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.GetResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.GetAndTouchRequest> __Marshaller_couchbase_kv_v1_GetAndTouchRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.GetAndTouchRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.GetAndTouchResponse> __Marshaller_couchbase_kv_v1_GetAndTouchResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.GetAndTouchResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.GetAndLockRequest> __Marshaller_couchbase_kv_v1_GetAndLockRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.GetAndLockRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.GetAndLockResponse> __Marshaller_couchbase_kv_v1_GetAndLockResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.GetAndLockResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.UnlockRequest> __Marshaller_couchbase_kv_v1_UnlockRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.UnlockRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.UnlockResponse> __Marshaller_couchbase_kv_v1_UnlockResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.UnlockResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.TouchRequest> __Marshaller_couchbase_kv_v1_TouchRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.TouchRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.TouchResponse> __Marshaller_couchbase_kv_v1_TouchResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.TouchResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.ExistsRequest> __Marshaller_couchbase_kv_v1_ExistsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.ExistsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.ExistsResponse> __Marshaller_couchbase_kv_v1_ExistsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.ExistsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.InsertRequest> __Marshaller_couchbase_kv_v1_InsertRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.InsertRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.InsertResponse> __Marshaller_couchbase_kv_v1_InsertResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.InsertResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.UpsertRequest> __Marshaller_couchbase_kv_v1_UpsertRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.UpsertRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.UpsertResponse> __Marshaller_couchbase_kv_v1_UpsertResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.UpsertResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.ReplaceRequest> __Marshaller_couchbase_kv_v1_ReplaceRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.ReplaceRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.ReplaceResponse> __Marshaller_couchbase_kv_v1_ReplaceResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.ReplaceResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.RemoveRequest> __Marshaller_couchbase_kv_v1_RemoveRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.RemoveRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.RemoveResponse> __Marshaller_couchbase_kv_v1_RemoveResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.RemoveResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.IncrementRequest> __Marshaller_couchbase_kv_v1_IncrementRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.IncrementRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.IncrementResponse> __Marshaller_couchbase_kv_v1_IncrementResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.IncrementResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.DecrementRequest> __Marshaller_couchbase_kv_v1_DecrementRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.DecrementRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.DecrementResponse> __Marshaller_couchbase_kv_v1_DecrementResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.DecrementResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.AppendRequest> __Marshaller_couchbase_kv_v1_AppendRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.AppendRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.AppendResponse> __Marshaller_couchbase_kv_v1_AppendResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.AppendResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.PrependRequest> __Marshaller_couchbase_kv_v1_PrependRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.PrependRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.PrependResponse> __Marshaller_couchbase_kv_v1_PrependResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.PrependResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.LookupInRequest> __Marshaller_couchbase_kv_v1_LookupInRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.LookupInRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.LookupInResponse> __Marshaller_couchbase_kv_v1_LookupInResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.LookupInResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.MutateInRequest> __Marshaller_couchbase_kv_v1_MutateInRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.MutateInRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.MutateInResponse> __Marshaller_couchbase_kv_v1_MutateInResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.MutateInResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.GetAllReplicasRequest> __Marshaller_couchbase_kv_v1_GetAllReplicasRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.GetAllReplicasRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Couchbase.Protostellar.KV.V1.GetAllReplicasResponse> __Marshaller_couchbase_kv_v1_GetAllReplicasResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Couchbase.Protostellar.KV.V1.GetAllReplicasResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.GetRequest, global::Couchbase.Protostellar.KV.V1.GetResponse> __Method_Get = new grpc::Method<global::Couchbase.Protostellar.KV.V1.GetRequest, global::Couchbase.Protostellar.KV.V1.GetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Get",
        __Marshaller_couchbase_kv_v1_GetRequest,
        __Marshaller_couchbase_kv_v1_GetResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.GetAndTouchRequest, global::Couchbase.Protostellar.KV.V1.GetAndTouchResponse> __Method_GetAndTouch = new grpc::Method<global::Couchbase.Protostellar.KV.V1.GetAndTouchRequest, global::Couchbase.Protostellar.KV.V1.GetAndTouchResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAndTouch",
        __Marshaller_couchbase_kv_v1_GetAndTouchRequest,
        __Marshaller_couchbase_kv_v1_GetAndTouchResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.GetAndLockRequest, global::Couchbase.Protostellar.KV.V1.GetAndLockResponse> __Method_GetAndLock = new grpc::Method<global::Couchbase.Protostellar.KV.V1.GetAndLockRequest, global::Couchbase.Protostellar.KV.V1.GetAndLockResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAndLock",
        __Marshaller_couchbase_kv_v1_GetAndLockRequest,
        __Marshaller_couchbase_kv_v1_GetAndLockResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.UnlockRequest, global::Couchbase.Protostellar.KV.V1.UnlockResponse> __Method_Unlock = new grpc::Method<global::Couchbase.Protostellar.KV.V1.UnlockRequest, global::Couchbase.Protostellar.KV.V1.UnlockResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Unlock",
        __Marshaller_couchbase_kv_v1_UnlockRequest,
        __Marshaller_couchbase_kv_v1_UnlockResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.TouchRequest, global::Couchbase.Protostellar.KV.V1.TouchResponse> __Method_Touch = new grpc::Method<global::Couchbase.Protostellar.KV.V1.TouchRequest, global::Couchbase.Protostellar.KV.V1.TouchResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Touch",
        __Marshaller_couchbase_kv_v1_TouchRequest,
        __Marshaller_couchbase_kv_v1_TouchResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.ExistsRequest, global::Couchbase.Protostellar.KV.V1.ExistsResponse> __Method_Exists = new grpc::Method<global::Couchbase.Protostellar.KV.V1.ExistsRequest, global::Couchbase.Protostellar.KV.V1.ExistsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Exists",
        __Marshaller_couchbase_kv_v1_ExistsRequest,
        __Marshaller_couchbase_kv_v1_ExistsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.InsertRequest, global::Couchbase.Protostellar.KV.V1.InsertResponse> __Method_Insert = new grpc::Method<global::Couchbase.Protostellar.KV.V1.InsertRequest, global::Couchbase.Protostellar.KV.V1.InsertResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Insert",
        __Marshaller_couchbase_kv_v1_InsertRequest,
        __Marshaller_couchbase_kv_v1_InsertResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.UpsertRequest, global::Couchbase.Protostellar.KV.V1.UpsertResponse> __Method_Upsert = new grpc::Method<global::Couchbase.Protostellar.KV.V1.UpsertRequest, global::Couchbase.Protostellar.KV.V1.UpsertResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Upsert",
        __Marshaller_couchbase_kv_v1_UpsertRequest,
        __Marshaller_couchbase_kv_v1_UpsertResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.ReplaceRequest, global::Couchbase.Protostellar.KV.V1.ReplaceResponse> __Method_Replace = new grpc::Method<global::Couchbase.Protostellar.KV.V1.ReplaceRequest, global::Couchbase.Protostellar.KV.V1.ReplaceResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Replace",
        __Marshaller_couchbase_kv_v1_ReplaceRequest,
        __Marshaller_couchbase_kv_v1_ReplaceResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.RemoveRequest, global::Couchbase.Protostellar.KV.V1.RemoveResponse> __Method_Remove = new grpc::Method<global::Couchbase.Protostellar.KV.V1.RemoveRequest, global::Couchbase.Protostellar.KV.V1.RemoveResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Remove",
        __Marshaller_couchbase_kv_v1_RemoveRequest,
        __Marshaller_couchbase_kv_v1_RemoveResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.IncrementRequest, global::Couchbase.Protostellar.KV.V1.IncrementResponse> __Method_Increment = new grpc::Method<global::Couchbase.Protostellar.KV.V1.IncrementRequest, global::Couchbase.Protostellar.KV.V1.IncrementResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Increment",
        __Marshaller_couchbase_kv_v1_IncrementRequest,
        __Marshaller_couchbase_kv_v1_IncrementResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.DecrementRequest, global::Couchbase.Protostellar.KV.V1.DecrementResponse> __Method_Decrement = new grpc::Method<global::Couchbase.Protostellar.KV.V1.DecrementRequest, global::Couchbase.Protostellar.KV.V1.DecrementResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Decrement",
        __Marshaller_couchbase_kv_v1_DecrementRequest,
        __Marshaller_couchbase_kv_v1_DecrementResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.AppendRequest, global::Couchbase.Protostellar.KV.V1.AppendResponse> __Method_Append = new grpc::Method<global::Couchbase.Protostellar.KV.V1.AppendRequest, global::Couchbase.Protostellar.KV.V1.AppendResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Append",
        __Marshaller_couchbase_kv_v1_AppendRequest,
        __Marshaller_couchbase_kv_v1_AppendResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.PrependRequest, global::Couchbase.Protostellar.KV.V1.PrependResponse> __Method_Prepend = new grpc::Method<global::Couchbase.Protostellar.KV.V1.PrependRequest, global::Couchbase.Protostellar.KV.V1.PrependResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Prepend",
        __Marshaller_couchbase_kv_v1_PrependRequest,
        __Marshaller_couchbase_kv_v1_PrependResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.LookupInRequest, global::Couchbase.Protostellar.KV.V1.LookupInResponse> __Method_LookupIn = new grpc::Method<global::Couchbase.Protostellar.KV.V1.LookupInRequest, global::Couchbase.Protostellar.KV.V1.LookupInResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "LookupIn",
        __Marshaller_couchbase_kv_v1_LookupInRequest,
        __Marshaller_couchbase_kv_v1_LookupInResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.MutateInRequest, global::Couchbase.Protostellar.KV.V1.MutateInResponse> __Method_MutateIn = new grpc::Method<global::Couchbase.Protostellar.KV.V1.MutateInRequest, global::Couchbase.Protostellar.KV.V1.MutateInResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "MutateIn",
        __Marshaller_couchbase_kv_v1_MutateInRequest,
        __Marshaller_couchbase_kv_v1_MutateInResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Couchbase.Protostellar.KV.V1.GetAllReplicasRequest, global::Couchbase.Protostellar.KV.V1.GetAllReplicasResponse> __Method_GetAllReplicas = new grpc::Method<global::Couchbase.Protostellar.KV.V1.GetAllReplicasRequest, global::Couchbase.Protostellar.KV.V1.GetAllReplicasResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetAllReplicas",
        __Marshaller_couchbase_kv_v1_GetAllReplicasRequest,
        __Marshaller_couchbase_kv_v1_GetAllReplicasResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Couchbase.Protostellar.KV.V1.KvReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for KvService</summary>
    public partial class KvServiceClient : grpc::ClientBase<KvServiceClient>
    {
      /// <summary>Creates a new client for KvService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public KvServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for KvService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public KvServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected KvServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected KvServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.GetResponse Get(global::Couchbase.Protostellar.KV.V1.GetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Get(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.GetResponse Get(global::Couchbase.Protostellar.KV.V1.GetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Get, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.GetResponse> GetAsync(global::Couchbase.Protostellar.KV.V1.GetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.GetResponse> GetAsync(global::Couchbase.Protostellar.KV.V1.GetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Get, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.GetAndTouchResponse GetAndTouch(global::Couchbase.Protostellar.KV.V1.GetAndTouchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAndTouch(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.GetAndTouchResponse GetAndTouch(global::Couchbase.Protostellar.KV.V1.GetAndTouchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAndTouch, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.GetAndTouchResponse> GetAndTouchAsync(global::Couchbase.Protostellar.KV.V1.GetAndTouchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAndTouchAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.GetAndTouchResponse> GetAndTouchAsync(global::Couchbase.Protostellar.KV.V1.GetAndTouchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAndTouch, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.GetAndLockResponse GetAndLock(global::Couchbase.Protostellar.KV.V1.GetAndLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAndLock(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.GetAndLockResponse GetAndLock(global::Couchbase.Protostellar.KV.V1.GetAndLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAndLock, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.GetAndLockResponse> GetAndLockAsync(global::Couchbase.Protostellar.KV.V1.GetAndLockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAndLockAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.GetAndLockResponse> GetAndLockAsync(global::Couchbase.Protostellar.KV.V1.GetAndLockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAndLock, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.UnlockResponse Unlock(global::Couchbase.Protostellar.KV.V1.UnlockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Unlock(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.UnlockResponse Unlock(global::Couchbase.Protostellar.KV.V1.UnlockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Unlock, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.UnlockResponse> UnlockAsync(global::Couchbase.Protostellar.KV.V1.UnlockRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UnlockAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.UnlockResponse> UnlockAsync(global::Couchbase.Protostellar.KV.V1.UnlockRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Unlock, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.TouchResponse Touch(global::Couchbase.Protostellar.KV.V1.TouchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Touch(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.TouchResponse Touch(global::Couchbase.Protostellar.KV.V1.TouchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Touch, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.TouchResponse> TouchAsync(global::Couchbase.Protostellar.KV.V1.TouchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TouchAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.TouchResponse> TouchAsync(global::Couchbase.Protostellar.KV.V1.TouchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Touch, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.ExistsResponse Exists(global::Couchbase.Protostellar.KV.V1.ExistsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Exists(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.ExistsResponse Exists(global::Couchbase.Protostellar.KV.V1.ExistsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Exists, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.ExistsResponse> ExistsAsync(global::Couchbase.Protostellar.KV.V1.ExistsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExistsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.ExistsResponse> ExistsAsync(global::Couchbase.Protostellar.KV.V1.ExistsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Exists, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.InsertResponse Insert(global::Couchbase.Protostellar.KV.V1.InsertRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Insert(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.InsertResponse Insert(global::Couchbase.Protostellar.KV.V1.InsertRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Insert, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.InsertResponse> InsertAsync(global::Couchbase.Protostellar.KV.V1.InsertRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.InsertResponse> InsertAsync(global::Couchbase.Protostellar.KV.V1.InsertRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Insert, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.UpsertResponse Upsert(global::Couchbase.Protostellar.KV.V1.UpsertRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Upsert(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.UpsertResponse Upsert(global::Couchbase.Protostellar.KV.V1.UpsertRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Upsert, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.UpsertResponse> UpsertAsync(global::Couchbase.Protostellar.KV.V1.UpsertRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpsertAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.UpsertResponse> UpsertAsync(global::Couchbase.Protostellar.KV.V1.UpsertRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Upsert, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.ReplaceResponse Replace(global::Couchbase.Protostellar.KV.V1.ReplaceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Replace(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.ReplaceResponse Replace(global::Couchbase.Protostellar.KV.V1.ReplaceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Replace, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.ReplaceResponse> ReplaceAsync(global::Couchbase.Protostellar.KV.V1.ReplaceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReplaceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.ReplaceResponse> ReplaceAsync(global::Couchbase.Protostellar.KV.V1.ReplaceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Replace, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.RemoveResponse Remove(global::Couchbase.Protostellar.KV.V1.RemoveRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Remove(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.RemoveResponse Remove(global::Couchbase.Protostellar.KV.V1.RemoveRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Remove, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.RemoveResponse> RemoveAsync(global::Couchbase.Protostellar.KV.V1.RemoveRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.RemoveResponse> RemoveAsync(global::Couchbase.Protostellar.KV.V1.RemoveRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Remove, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.IncrementResponse Increment(global::Couchbase.Protostellar.KV.V1.IncrementRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Increment(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.IncrementResponse Increment(global::Couchbase.Protostellar.KV.V1.IncrementRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Increment, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.IncrementResponse> IncrementAsync(global::Couchbase.Protostellar.KV.V1.IncrementRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return IncrementAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.IncrementResponse> IncrementAsync(global::Couchbase.Protostellar.KV.V1.IncrementRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Increment, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.DecrementResponse Decrement(global::Couchbase.Protostellar.KV.V1.DecrementRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Decrement(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.DecrementResponse Decrement(global::Couchbase.Protostellar.KV.V1.DecrementRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Decrement, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.DecrementResponse> DecrementAsync(global::Couchbase.Protostellar.KV.V1.DecrementRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DecrementAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.DecrementResponse> DecrementAsync(global::Couchbase.Protostellar.KV.V1.DecrementRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Decrement, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.AppendResponse Append(global::Couchbase.Protostellar.KV.V1.AppendRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Append(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.AppendResponse Append(global::Couchbase.Protostellar.KV.V1.AppendRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Append, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.AppendResponse> AppendAsync(global::Couchbase.Protostellar.KV.V1.AppendRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AppendAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.AppendResponse> AppendAsync(global::Couchbase.Protostellar.KV.V1.AppendRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Append, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.PrependResponse Prepend(global::Couchbase.Protostellar.KV.V1.PrependRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Prepend(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.PrependResponse Prepend(global::Couchbase.Protostellar.KV.V1.PrependRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Prepend, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.PrependResponse> PrependAsync(global::Couchbase.Protostellar.KV.V1.PrependRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PrependAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.PrependResponse> PrependAsync(global::Couchbase.Protostellar.KV.V1.PrependRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Prepend, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.LookupInResponse LookupIn(global::Couchbase.Protostellar.KV.V1.LookupInRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LookupIn(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.LookupInResponse LookupIn(global::Couchbase.Protostellar.KV.V1.LookupInRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_LookupIn, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.LookupInResponse> LookupInAsync(global::Couchbase.Protostellar.KV.V1.LookupInRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LookupInAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.LookupInResponse> LookupInAsync(global::Couchbase.Protostellar.KV.V1.LookupInRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_LookupIn, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.MutateInResponse MutateIn(global::Couchbase.Protostellar.KV.V1.MutateInRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MutateIn(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Couchbase.Protostellar.KV.V1.MutateInResponse MutateIn(global::Couchbase.Protostellar.KV.V1.MutateInRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_MutateIn, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.MutateInResponse> MutateInAsync(global::Couchbase.Protostellar.KV.V1.MutateInRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MutateInAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Couchbase.Protostellar.KV.V1.MutateInResponse> MutateInAsync(global::Couchbase.Protostellar.KV.V1.MutateInRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_MutateIn, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Couchbase.Protostellar.KV.V1.GetAllReplicasResponse> GetAllReplicas(global::Couchbase.Protostellar.KV.V1.GetAllReplicasRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllReplicas(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Couchbase.Protostellar.KV.V1.GetAllReplicasResponse> GetAllReplicas(global::Couchbase.Protostellar.KV.V1.GetAllReplicasRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetAllReplicas, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override KvServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new KvServiceClient(configuration);
      }
    }

  }
}
#endregion
