// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: couchbase/analytics/v1/analytics.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Couchbase.Protostellar.Analytics.V1 {

  /// <summary>Holder for reflection information generated from couchbase/analytics/v1/analytics.proto</summary>
  public static partial class AnalyticsReflection {

    #region Descriptor
    /// <summary>File descriptor for couchbase/analytics/v1/analytics.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AnalyticsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZjb3VjaGJhc2UvYW5hbHl0aWNzL3YxL2FuYWx5dGljcy5wcm90bxIWY291",
            "Y2hiYXNlLmFuYWx5dGljcy52MRoeZ29vZ2xlL3Byb3RvYnVmL2R1cmF0aW9u",
            "LnByb3RvIvwEChVBbmFseXRpY3NRdWVyeVJlcXVlc3QSGAoLYnVja2V0X25h",
            "bWUYCCABKAlIAIgBARIXCgpzY29wZV9uYW1lGAkgASgJSAGIAQESEQoJc3Rh",
            "dGVtZW50GAEgASgJEhYKCXJlYWRfb25seRgCIAEoCEgCiAEBEh4KEWNsaWVu",
            "dF9jb250ZXh0X2lkGAMgASgJSAOIAQESFQoIcHJpb3JpdHkYBCABKAhIBIgB",
            "ARJcChBzY2FuX2NvbnNpc3RlbmN5GAUgASgOMj0uY291Y2hiYXNlLmFuYWx5",
            "dGljcy52MS5BbmFseXRpY3NRdWVyeVJlcXVlc3QuU2NhbkNvbnNpc3RlbmN5",
            "SAWIAQESHQoVcG9zaXRpb25hbF9wYXJhbWV0ZXJzGAYgAygMElwKEG5hbWVk",
            "X3BhcmFtZXRlcnMYByADKAsyQi5jb3VjaGJhc2UuYW5hbHl0aWNzLnYxLkFu",
            "YWx5dGljc1F1ZXJ5UmVxdWVzdC5OYW1lZFBhcmFtZXRlcnNFbnRyeRo2ChRO",
            "YW1lZFBhcmFtZXRlcnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiAB",
            "KAw6AjgBIlYKD1NjYW5Db25zaXN0ZW5jeRIgChxTQ0FOX0NPTlNJU1RFTkNZ",
            "X05PVF9CT1VOREVEEAASIQodU0NBTl9DT05TSVNURU5DWV9SRVFVRVNUX1BM",
            "VVMQAUIOCgxfYnVja2V0X25hbWVCDQoLX3Njb3BlX25hbWVCDAoKX3JlYWRf",
            "b25seUIUChJfY2xpZW50X2NvbnRleHRfaWRCCwoJX3ByaW9yaXR5QhMKEV9z",
            "Y2FuX2NvbnNpc3RlbmN5IrgFChZBbmFseXRpY3NRdWVyeVJlc3BvbnNlEgwK",
            "BHJvd3MYASADKAwSTwoJbWV0YV9kYXRhGAIgASgLMjcuY291Y2hiYXNlLmFu",
            "YWx5dGljcy52MS5BbmFseXRpY3NRdWVyeVJlc3BvbnNlLk1ldGFEYXRhSACI",
            "AQEaiwIKB01ldHJpY3MSLwoMZWxhcHNlZF90aW1lGAEgASgLMhkuZ29vZ2xl",
            "LnByb3RvYnVmLkR1cmF0aW9uEjEKDmV4ZWN1dGlvbl90aW1lGAIgASgLMhku",
            "Z29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uEhQKDHJlc3VsdF9jb3VudBgDIAEo",
            "BBITCgtyZXN1bHRfc2l6ZRgEIAEoBBIWCg5tdXRhdGlvbl9jb3VudBgFIAEo",
            "BBISCgpzb3J0X2NvdW50GAYgASgEEhMKC2Vycm9yX2NvdW50GAcgASgEEhUK",
            "DXdhcm5pbmdfY291bnQYCCABKAQSGQoRcHJvY2Vzc2VkX29iamVjdHMYCSAB",
            "KAQaogIKCE1ldGFEYXRhEhIKCnJlcXVlc3RfaWQYASABKAkSGQoRY2xpZW50",
            "X2NvbnRleHRfaWQYAiABKAkSRwoHbWV0cmljcxgDIAEoCzI2LmNvdWNoYmFz",
            "ZS5hbmFseXRpY3MudjEuQW5hbHl0aWNzUXVlcnlSZXNwb25zZS5NZXRyaWNz",
            "EhEKCXNpZ25hdHVyZRgEIAEoDBJRCgh3YXJuaW5ncxgFIAMoCzI/LmNvdWNo",
            "YmFzZS5hbmFseXRpY3MudjEuQW5hbHl0aWNzUXVlcnlSZXNwb25zZS5NZXRh",
            "RGF0YS5XYXJuaW5nEg4KBnN0YXR1cxgGIAEoCRooCgdXYXJuaW5nEgwKBGNv",
            "ZGUYASABKA0SDwoHbWVzc2FnZRgCIAEoCUIMCgpfbWV0YV9kYXRhMocBChBB",
            "bmFseXRpY3NTZXJ2aWNlEnMKDkFuYWx5dGljc1F1ZXJ5Ei0uY291Y2hiYXNl",
            "LmFuYWx5dGljcy52MS5BbmFseXRpY3NRdWVyeVJlcXVlc3QaLi5jb3VjaGJh",
            "c2UuYW5hbHl0aWNzLnYxLkFuYWx5dGljc1F1ZXJ5UmVzcG9uc2UiADABQoQC",
            "Ci5jb20uY291Y2hiYXNlLmNsaWVudC5wcm90b3N0ZWxsYXIuYW5hbHl0aWNz",
            "LnYxUAFaRmdpdGh1Yi5jb20vY291Y2hiYXNlL2dvcHJvdG9zdGVsbGFyL2dl",
            "bnByb3RvL2FuYWx5dGljc192MTthbmFseXRpY3NfdjGqAiNDb3VjaGJhc2Uu",
            "UHJvdG9zdGVsbGFyLkFuYWx5dGljcy5WMcoCLUNvdWNoYmFzZVxQcm90b3N0",
            "ZWxsYXJcR2VuZXJhdGVkXEFuYWx5dGljc1xWMeoCMUNvdWNoYmFzZTo6UHJv",
            "dG9zdGVsbGFyOjpHZW5lcmF0ZWQ6OkFuYWx5dGljczo6VjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryRequest), global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryRequest.Parser, new[]{ "BucketName", "ScopeName", "Statement", "ReadOnly", "ClientContextId", "Priority", "ScanConsistency", "PositionalParameters", "NamedParameters" }, new[]{ "BucketName", "ScopeName", "ReadOnly", "ClientContextId", "Priority", "ScanConsistency" }, new[]{ typeof(global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryRequest.Types.ScanConsistency) }, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse), global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Parser, new[]{ "Rows", "MetaData" }, new[]{ "MetaData" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.Metrics), global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.Metrics.Parser, new[]{ "ElapsedTime", "ExecutionTime", "ResultCount", "ResultSize", "MutationCount", "SortCount", "ErrorCount", "WarningCount", "ProcessedObjects" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.MetaData), global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.MetaData.Parser, new[]{ "RequestId", "ClientContextId", "Metrics", "Signature", "Warnings", "Status" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.MetaData.Types.Warning), global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.MetaData.Types.Warning.Parser, new[]{ "Code", "Message" }, null, null, null, null)})})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AnalyticsQueryRequest : pb::IMessage<AnalyticsQueryRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AnalyticsQueryRequest> _parser = new pb::MessageParser<AnalyticsQueryRequest>(() => new AnalyticsQueryRequest());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AnalyticsQueryRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Couchbase.Protostellar.Analytics.V1.AnalyticsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnalyticsQueryRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnalyticsQueryRequest(AnalyticsQueryRequest other) : this() {
      _hasBits0 = other._hasBits0;
      bucketName_ = other.bucketName_;
      scopeName_ = other.scopeName_;
      statement_ = other.statement_;
      readOnly_ = other.readOnly_;
      clientContextId_ = other.clientContextId_;
      priority_ = other.priority_;
      scanConsistency_ = other.scanConsistency_;
      positionalParameters_ = other.positionalParameters_.Clone();
      namedParameters_ = other.namedParameters_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnalyticsQueryRequest Clone() {
      return new AnalyticsQueryRequest(this);
    }

    /// <summary>Field number for the "bucket_name" field.</summary>
    public const int BucketNameFieldNumber = 8;
    private readonly static string BucketNameDefaultValue = "";

    private string bucketName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BucketName {
      get { return bucketName_ ?? BucketNameDefaultValue; }
      set {
        bucketName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "bucket_name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBucketName {
      get { return bucketName_ != null; }
    }
    /// <summary>Clears the value of the "bucket_name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBucketName() {
      bucketName_ = null;
    }

    /// <summary>Field number for the "scope_name" field.</summary>
    public const int ScopeNameFieldNumber = 9;
    private readonly static string ScopeNameDefaultValue = "";

    private string scopeName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ScopeName {
      get { return scopeName_ ?? ScopeNameDefaultValue; }
      set {
        scopeName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "scope_name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasScopeName {
      get { return scopeName_ != null; }
    }
    /// <summary>Clears the value of the "scope_name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearScopeName() {
      scopeName_ = null;
    }

    /// <summary>Field number for the "statement" field.</summary>
    public const int StatementFieldNumber = 1;
    private string statement_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Statement {
      get { return statement_; }
      set {
        statement_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "read_only" field.</summary>
    public const int ReadOnlyFieldNumber = 2;
    private readonly static bool ReadOnlyDefaultValue = false;

    private bool readOnly_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ReadOnly {
      get { if ((_hasBits0 & 1) != 0) { return readOnly_; } else { return ReadOnlyDefaultValue; } }
      set {
        _hasBits0 |= 1;
        readOnly_ = value;
      }
    }
    /// <summary>Gets whether the "read_only" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasReadOnly {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "read_only" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearReadOnly() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "client_context_id" field.</summary>
    public const int ClientContextIdFieldNumber = 3;
    private readonly static string ClientContextIdDefaultValue = "";

    private string clientContextId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientContextId {
      get { return clientContextId_ ?? ClientContextIdDefaultValue; }
      set {
        clientContextId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "client_context_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasClientContextId {
      get { return clientContextId_ != null; }
    }
    /// <summary>Clears the value of the "client_context_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearClientContextId() {
      clientContextId_ = null;
    }

    /// <summary>Field number for the "priority" field.</summary>
    public const int PriorityFieldNumber = 4;
    private readonly static bool PriorityDefaultValue = false;

    private bool priority_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Priority {
      get { if ((_hasBits0 & 2) != 0) { return priority_; } else { return PriorityDefaultValue; } }
      set {
        _hasBits0 |= 2;
        priority_ = value;
      }
    }
    /// <summary>Gets whether the "priority" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPriority {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "priority" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPriority() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "scan_consistency" field.</summary>
    public const int ScanConsistencyFieldNumber = 5;
    private readonly static global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryRequest.Types.ScanConsistency ScanConsistencyDefaultValue = global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryRequest.Types.ScanConsistency.NotBounded;

    private global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryRequest.Types.ScanConsistency scanConsistency_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryRequest.Types.ScanConsistency ScanConsistency {
      get { if ((_hasBits0 & 4) != 0) { return scanConsistency_; } else { return ScanConsistencyDefaultValue; } }
      set {
        _hasBits0 |= 4;
        scanConsistency_ = value;
      }
    }
    /// <summary>Gets whether the "scan_consistency" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasScanConsistency {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "scan_consistency" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearScanConsistency() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "positional_parameters" field.</summary>
    public const int PositionalParametersFieldNumber = 6;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_positionalParameters_codec
        = pb::FieldCodec.ForBytes(50);
    private readonly pbc::RepeatedField<pb::ByteString> positionalParameters_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<pb::ByteString> PositionalParameters {
      get { return positionalParameters_; }
    }

    /// <summary>Field number for the "named_parameters" field.</summary>
    public const int NamedParametersFieldNumber = 7;
    private static readonly pbc::MapField<string, pb::ByteString>.Codec _map_namedParameters_codec
        = new pbc::MapField<string, pb::ByteString>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForBytes(18, pb::ByteString.Empty), 58);
    private readonly pbc::MapField<string, pb::ByteString> namedParameters_ = new pbc::MapField<string, pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, pb::ByteString> NamedParameters {
      get { return namedParameters_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AnalyticsQueryRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AnalyticsQueryRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BucketName != other.BucketName) return false;
      if (ScopeName != other.ScopeName) return false;
      if (Statement != other.Statement) return false;
      if (ReadOnly != other.ReadOnly) return false;
      if (ClientContextId != other.ClientContextId) return false;
      if (Priority != other.Priority) return false;
      if (ScanConsistency != other.ScanConsistency) return false;
      if(!positionalParameters_.Equals(other.positionalParameters_)) return false;
      if (!NamedParameters.Equals(other.NamedParameters)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasBucketName) hash ^= BucketName.GetHashCode();
      if (HasScopeName) hash ^= ScopeName.GetHashCode();
      if (Statement.Length != 0) hash ^= Statement.GetHashCode();
      if (HasReadOnly) hash ^= ReadOnly.GetHashCode();
      if (HasClientContextId) hash ^= ClientContextId.GetHashCode();
      if (HasPriority) hash ^= Priority.GetHashCode();
      if (HasScanConsistency) hash ^= ScanConsistency.GetHashCode();
      hash ^= positionalParameters_.GetHashCode();
      hash ^= NamedParameters.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Statement.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Statement);
      }
      if (HasReadOnly) {
        output.WriteRawTag(16);
        output.WriteBool(ReadOnly);
      }
      if (HasClientContextId) {
        output.WriteRawTag(26);
        output.WriteString(ClientContextId);
      }
      if (HasPriority) {
        output.WriteRawTag(32);
        output.WriteBool(Priority);
      }
      if (HasScanConsistency) {
        output.WriteRawTag(40);
        output.WriteEnum((int) ScanConsistency);
      }
      positionalParameters_.WriteTo(output, _repeated_positionalParameters_codec);
      namedParameters_.WriteTo(output, _map_namedParameters_codec);
      if (HasBucketName) {
        output.WriteRawTag(66);
        output.WriteString(BucketName);
      }
      if (HasScopeName) {
        output.WriteRawTag(74);
        output.WriteString(ScopeName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Statement.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Statement);
      }
      if (HasReadOnly) {
        output.WriteRawTag(16);
        output.WriteBool(ReadOnly);
      }
      if (HasClientContextId) {
        output.WriteRawTag(26);
        output.WriteString(ClientContextId);
      }
      if (HasPriority) {
        output.WriteRawTag(32);
        output.WriteBool(Priority);
      }
      if (HasScanConsistency) {
        output.WriteRawTag(40);
        output.WriteEnum((int) ScanConsistency);
      }
      positionalParameters_.WriteTo(ref output, _repeated_positionalParameters_codec);
      namedParameters_.WriteTo(ref output, _map_namedParameters_codec);
      if (HasBucketName) {
        output.WriteRawTag(66);
        output.WriteString(BucketName);
      }
      if (HasScopeName) {
        output.WriteRawTag(74);
        output.WriteString(ScopeName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasBucketName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BucketName);
      }
      if (HasScopeName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ScopeName);
      }
      if (Statement.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Statement);
      }
      if (HasReadOnly) {
        size += 1 + 1;
      }
      if (HasClientContextId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientContextId);
      }
      if (HasPriority) {
        size += 1 + 1;
      }
      if (HasScanConsistency) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ScanConsistency);
      }
      size += positionalParameters_.CalculateSize(_repeated_positionalParameters_codec);
      size += namedParameters_.CalculateSize(_map_namedParameters_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AnalyticsQueryRequest other) {
      if (other == null) {
        return;
      }
      if (other.HasBucketName) {
        BucketName = other.BucketName;
      }
      if (other.HasScopeName) {
        ScopeName = other.ScopeName;
      }
      if (other.Statement.Length != 0) {
        Statement = other.Statement;
      }
      if (other.HasReadOnly) {
        ReadOnly = other.ReadOnly;
      }
      if (other.HasClientContextId) {
        ClientContextId = other.ClientContextId;
      }
      if (other.HasPriority) {
        Priority = other.Priority;
      }
      if (other.HasScanConsistency) {
        ScanConsistency = other.ScanConsistency;
      }
      positionalParameters_.Add(other.positionalParameters_);
      namedParameters_.MergeFrom(other.namedParameters_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Statement = input.ReadString();
            break;
          }
          case 16: {
            ReadOnly = input.ReadBool();
            break;
          }
          case 26: {
            ClientContextId = input.ReadString();
            break;
          }
          case 32: {
            Priority = input.ReadBool();
            break;
          }
          case 40: {
            ScanConsistency = (global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryRequest.Types.ScanConsistency) input.ReadEnum();
            break;
          }
          case 50: {
            positionalParameters_.AddEntriesFrom(input, _repeated_positionalParameters_codec);
            break;
          }
          case 58: {
            namedParameters_.AddEntriesFrom(input, _map_namedParameters_codec);
            break;
          }
          case 66: {
            BucketName = input.ReadString();
            break;
          }
          case 74: {
            ScopeName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Statement = input.ReadString();
            break;
          }
          case 16: {
            ReadOnly = input.ReadBool();
            break;
          }
          case 26: {
            ClientContextId = input.ReadString();
            break;
          }
          case 32: {
            Priority = input.ReadBool();
            break;
          }
          case 40: {
            ScanConsistency = (global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryRequest.Types.ScanConsistency) input.ReadEnum();
            break;
          }
          case 50: {
            positionalParameters_.AddEntriesFrom(ref input, _repeated_positionalParameters_codec);
            break;
          }
          case 58: {
            namedParameters_.AddEntriesFrom(ref input, _map_namedParameters_codec);
            break;
          }
          case 66: {
            BucketName = input.ReadString();
            break;
          }
          case 74: {
            ScopeName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AnalyticsQueryRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ScanConsistency {
        [pbr::OriginalName("SCAN_CONSISTENCY_NOT_BOUNDED")] NotBounded = 0,
        [pbr::OriginalName("SCAN_CONSISTENCY_REQUEST_PLUS")] RequestPlus = 1,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AnalyticsQueryResponse : pb::IMessage<AnalyticsQueryResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AnalyticsQueryResponse> _parser = new pb::MessageParser<AnalyticsQueryResponse>(() => new AnalyticsQueryResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AnalyticsQueryResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Couchbase.Protostellar.Analytics.V1.AnalyticsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnalyticsQueryResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnalyticsQueryResponse(AnalyticsQueryResponse other) : this() {
      rows_ = other.rows_.Clone();
      metaData_ = other.metaData_ != null ? other.metaData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnalyticsQueryResponse Clone() {
      return new AnalyticsQueryResponse(this);
    }

    /// <summary>Field number for the "rows" field.</summary>
    public const int RowsFieldNumber = 1;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_rows_codec
        = pb::FieldCodec.ForBytes(10);
    private readonly pbc::RepeatedField<pb::ByteString> rows_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<pb::ByteString> Rows {
      get { return rows_; }
    }

    /// <summary>Field number for the "meta_data" field.</summary>
    public const int MetaDataFieldNumber = 2;
    private global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.MetaData metaData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.MetaData MetaData {
      get { return metaData_; }
      set {
        metaData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AnalyticsQueryResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AnalyticsQueryResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!rows_.Equals(other.rows_)) return false;
      if (!object.Equals(MetaData, other.MetaData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= rows_.GetHashCode();
      if (metaData_ != null) hash ^= MetaData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      rows_.WriteTo(output, _repeated_rows_codec);
      if (metaData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MetaData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      rows_.WriteTo(ref output, _repeated_rows_codec);
      if (metaData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MetaData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += rows_.CalculateSize(_repeated_rows_codec);
      if (metaData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MetaData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AnalyticsQueryResponse other) {
      if (other == null) {
        return;
      }
      rows_.Add(other.rows_);
      if (other.metaData_ != null) {
        if (metaData_ == null) {
          MetaData = new global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.MetaData();
        }
        MetaData.MergeFrom(other.MetaData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            rows_.AddEntriesFrom(input, _repeated_rows_codec);
            break;
          }
          case 18: {
            if (metaData_ == null) {
              MetaData = new global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.MetaData();
            }
            input.ReadMessage(MetaData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            rows_.AddEntriesFrom(ref input, _repeated_rows_codec);
            break;
          }
          case 18: {
            if (metaData_ == null) {
              MetaData = new global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.MetaData();
            }
            input.ReadMessage(MetaData);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AnalyticsQueryResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Metrics : pb::IMessage<Metrics>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Metrics> _parser = new pb::MessageParser<Metrics>(() => new Metrics());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Metrics> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Metrics() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Metrics(Metrics other) : this() {
          elapsedTime_ = other.elapsedTime_ != null ? other.elapsedTime_.Clone() : null;
          executionTime_ = other.executionTime_ != null ? other.executionTime_.Clone() : null;
          resultCount_ = other.resultCount_;
          resultSize_ = other.resultSize_;
          mutationCount_ = other.mutationCount_;
          sortCount_ = other.sortCount_;
          errorCount_ = other.errorCount_;
          warningCount_ = other.warningCount_;
          processedObjects_ = other.processedObjects_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Metrics Clone() {
          return new Metrics(this);
        }

        /// <summary>Field number for the "elapsed_time" field.</summary>
        public const int ElapsedTimeFieldNumber = 1;
        private global::Google.Protobuf.WellKnownTypes.Duration elapsedTime_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Google.Protobuf.WellKnownTypes.Duration ElapsedTime {
          get { return elapsedTime_; }
          set {
            elapsedTime_ = value;
          }
        }

        /// <summary>Field number for the "execution_time" field.</summary>
        public const int ExecutionTimeFieldNumber = 2;
        private global::Google.Protobuf.WellKnownTypes.Duration executionTime_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Google.Protobuf.WellKnownTypes.Duration ExecutionTime {
          get { return executionTime_; }
          set {
            executionTime_ = value;
          }
        }

        /// <summary>Field number for the "result_count" field.</summary>
        public const int ResultCountFieldNumber = 3;
        private ulong resultCount_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong ResultCount {
          get { return resultCount_; }
          set {
            resultCount_ = value;
          }
        }

        /// <summary>Field number for the "result_size" field.</summary>
        public const int ResultSizeFieldNumber = 4;
        private ulong resultSize_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong ResultSize {
          get { return resultSize_; }
          set {
            resultSize_ = value;
          }
        }

        /// <summary>Field number for the "mutation_count" field.</summary>
        public const int MutationCountFieldNumber = 5;
        private ulong mutationCount_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong MutationCount {
          get { return mutationCount_; }
          set {
            mutationCount_ = value;
          }
        }

        /// <summary>Field number for the "sort_count" field.</summary>
        public const int SortCountFieldNumber = 6;
        private ulong sortCount_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong SortCount {
          get { return sortCount_; }
          set {
            sortCount_ = value;
          }
        }

        /// <summary>Field number for the "error_count" field.</summary>
        public const int ErrorCountFieldNumber = 7;
        private ulong errorCount_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong ErrorCount {
          get { return errorCount_; }
          set {
            errorCount_ = value;
          }
        }

        /// <summary>Field number for the "warning_count" field.</summary>
        public const int WarningCountFieldNumber = 8;
        private ulong warningCount_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong WarningCount {
          get { return warningCount_; }
          set {
            warningCount_ = value;
          }
        }

        /// <summary>Field number for the "processed_objects" field.</summary>
        public const int ProcessedObjectsFieldNumber = 9;
        private ulong processedObjects_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong ProcessedObjects {
          get { return processedObjects_; }
          set {
            processedObjects_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Metrics);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Metrics other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(ElapsedTime, other.ElapsedTime)) return false;
          if (!object.Equals(ExecutionTime, other.ExecutionTime)) return false;
          if (ResultCount != other.ResultCount) return false;
          if (ResultSize != other.ResultSize) return false;
          if (MutationCount != other.MutationCount) return false;
          if (SortCount != other.SortCount) return false;
          if (ErrorCount != other.ErrorCount) return false;
          if (WarningCount != other.WarningCount) return false;
          if (ProcessedObjects != other.ProcessedObjects) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (elapsedTime_ != null) hash ^= ElapsedTime.GetHashCode();
          if (executionTime_ != null) hash ^= ExecutionTime.GetHashCode();
          if (ResultCount != 0UL) hash ^= ResultCount.GetHashCode();
          if (ResultSize != 0UL) hash ^= ResultSize.GetHashCode();
          if (MutationCount != 0UL) hash ^= MutationCount.GetHashCode();
          if (SortCount != 0UL) hash ^= SortCount.GetHashCode();
          if (ErrorCount != 0UL) hash ^= ErrorCount.GetHashCode();
          if (WarningCount != 0UL) hash ^= WarningCount.GetHashCode();
          if (ProcessedObjects != 0UL) hash ^= ProcessedObjects.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (elapsedTime_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(ElapsedTime);
          }
          if (executionTime_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(ExecutionTime);
          }
          if (ResultCount != 0UL) {
            output.WriteRawTag(24);
            output.WriteUInt64(ResultCount);
          }
          if (ResultSize != 0UL) {
            output.WriteRawTag(32);
            output.WriteUInt64(ResultSize);
          }
          if (MutationCount != 0UL) {
            output.WriteRawTag(40);
            output.WriteUInt64(MutationCount);
          }
          if (SortCount != 0UL) {
            output.WriteRawTag(48);
            output.WriteUInt64(SortCount);
          }
          if (ErrorCount != 0UL) {
            output.WriteRawTag(56);
            output.WriteUInt64(ErrorCount);
          }
          if (WarningCount != 0UL) {
            output.WriteRawTag(64);
            output.WriteUInt64(WarningCount);
          }
          if (ProcessedObjects != 0UL) {
            output.WriteRawTag(72);
            output.WriteUInt64(ProcessedObjects);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (elapsedTime_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(ElapsedTime);
          }
          if (executionTime_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(ExecutionTime);
          }
          if (ResultCount != 0UL) {
            output.WriteRawTag(24);
            output.WriteUInt64(ResultCount);
          }
          if (ResultSize != 0UL) {
            output.WriteRawTag(32);
            output.WriteUInt64(ResultSize);
          }
          if (MutationCount != 0UL) {
            output.WriteRawTag(40);
            output.WriteUInt64(MutationCount);
          }
          if (SortCount != 0UL) {
            output.WriteRawTag(48);
            output.WriteUInt64(SortCount);
          }
          if (ErrorCount != 0UL) {
            output.WriteRawTag(56);
            output.WriteUInt64(ErrorCount);
          }
          if (WarningCount != 0UL) {
            output.WriteRawTag(64);
            output.WriteUInt64(WarningCount);
          }
          if (ProcessedObjects != 0UL) {
            output.WriteRawTag(72);
            output.WriteUInt64(ProcessedObjects);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (elapsedTime_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(ElapsedTime);
          }
          if (executionTime_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExecutionTime);
          }
          if (ResultCount != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ResultCount);
          }
          if (ResultSize != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ResultSize);
          }
          if (MutationCount != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MutationCount);
          }
          if (SortCount != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SortCount);
          }
          if (ErrorCount != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ErrorCount);
          }
          if (WarningCount != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(WarningCount);
          }
          if (ProcessedObjects != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ProcessedObjects);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Metrics other) {
          if (other == null) {
            return;
          }
          if (other.elapsedTime_ != null) {
            if (elapsedTime_ == null) {
              ElapsedTime = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            ElapsedTime.MergeFrom(other.ElapsedTime);
          }
          if (other.executionTime_ != null) {
            if (executionTime_ == null) {
              ExecutionTime = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            ExecutionTime.MergeFrom(other.ExecutionTime);
          }
          if (other.ResultCount != 0UL) {
            ResultCount = other.ResultCount;
          }
          if (other.ResultSize != 0UL) {
            ResultSize = other.ResultSize;
          }
          if (other.MutationCount != 0UL) {
            MutationCount = other.MutationCount;
          }
          if (other.SortCount != 0UL) {
            SortCount = other.SortCount;
          }
          if (other.ErrorCount != 0UL) {
            ErrorCount = other.ErrorCount;
          }
          if (other.WarningCount != 0UL) {
            WarningCount = other.WarningCount;
          }
          if (other.ProcessedObjects != 0UL) {
            ProcessedObjects = other.ProcessedObjects;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (elapsedTime_ == null) {
                  ElapsedTime = new global::Google.Protobuf.WellKnownTypes.Duration();
                }
                input.ReadMessage(ElapsedTime);
                break;
              }
              case 18: {
                if (executionTime_ == null) {
                  ExecutionTime = new global::Google.Protobuf.WellKnownTypes.Duration();
                }
                input.ReadMessage(ExecutionTime);
                break;
              }
              case 24: {
                ResultCount = input.ReadUInt64();
                break;
              }
              case 32: {
                ResultSize = input.ReadUInt64();
                break;
              }
              case 40: {
                MutationCount = input.ReadUInt64();
                break;
              }
              case 48: {
                SortCount = input.ReadUInt64();
                break;
              }
              case 56: {
                ErrorCount = input.ReadUInt64();
                break;
              }
              case 64: {
                WarningCount = input.ReadUInt64();
                break;
              }
              case 72: {
                ProcessedObjects = input.ReadUInt64();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                if (elapsedTime_ == null) {
                  ElapsedTime = new global::Google.Protobuf.WellKnownTypes.Duration();
                }
                input.ReadMessage(ElapsedTime);
                break;
              }
              case 18: {
                if (executionTime_ == null) {
                  ExecutionTime = new global::Google.Protobuf.WellKnownTypes.Duration();
                }
                input.ReadMessage(ExecutionTime);
                break;
              }
              case 24: {
                ResultCount = input.ReadUInt64();
                break;
              }
              case 32: {
                ResultSize = input.ReadUInt64();
                break;
              }
              case 40: {
                MutationCount = input.ReadUInt64();
                break;
              }
              case 48: {
                SortCount = input.ReadUInt64();
                break;
              }
              case 56: {
                ErrorCount = input.ReadUInt64();
                break;
              }
              case 64: {
                WarningCount = input.ReadUInt64();
                break;
              }
              case 72: {
                ProcessedObjects = input.ReadUInt64();
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class MetaData : pb::IMessage<MetaData>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<MetaData> _parser = new pb::MessageParser<MetaData>(() => new MetaData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<MetaData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public MetaData() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public MetaData(MetaData other) : this() {
          requestId_ = other.requestId_;
          clientContextId_ = other.clientContextId_;
          metrics_ = other.metrics_ != null ? other.metrics_.Clone() : null;
          signature_ = other.signature_;
          warnings_ = other.warnings_.Clone();
          status_ = other.status_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public MetaData Clone() {
          return new MetaData(this);
        }

        /// <summary>Field number for the "request_id" field.</summary>
        public const int RequestIdFieldNumber = 1;
        private string requestId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string RequestId {
          get { return requestId_; }
          set {
            requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "client_context_id" field.</summary>
        public const int ClientContextIdFieldNumber = 2;
        private string clientContextId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ClientContextId {
          get { return clientContextId_; }
          set {
            clientContextId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "metrics" field.</summary>
        public const int MetricsFieldNumber = 3;
        private global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.Metrics metrics_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.Metrics Metrics {
          get { return metrics_; }
          set {
            metrics_ = value;
          }
        }

        /// <summary>Field number for the "signature" field.</summary>
        public const int SignatureFieldNumber = 4;
        private pb::ByteString signature_ = pb::ByteString.Empty;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pb::ByteString Signature {
          get { return signature_; }
          set {
            signature_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "warnings" field.</summary>
        public const int WarningsFieldNumber = 5;
        private static readonly pb::FieldCodec<global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.MetaData.Types.Warning> _repeated_warnings_codec
            = pb::FieldCodec.ForMessage(42, global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.MetaData.Types.Warning.Parser);
        private readonly pbc::RepeatedField<global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.MetaData.Types.Warning> warnings_ = new pbc::RepeatedField<global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.MetaData.Types.Warning>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.MetaData.Types.Warning> Warnings {
          get { return warnings_; }
        }

        /// <summary>Field number for the "status" field.</summary>
        public const int StatusFieldNumber = 6;
        private string status_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Status {
          get { return status_; }
          set {
            status_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as MetaData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(MetaData other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (RequestId != other.RequestId) return false;
          if (ClientContextId != other.ClientContextId) return false;
          if (!object.Equals(Metrics, other.Metrics)) return false;
          if (Signature != other.Signature) return false;
          if(!warnings_.Equals(other.warnings_)) return false;
          if (Status != other.Status) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
          if (ClientContextId.Length != 0) hash ^= ClientContextId.GetHashCode();
          if (metrics_ != null) hash ^= Metrics.GetHashCode();
          if (Signature.Length != 0) hash ^= Signature.GetHashCode();
          hash ^= warnings_.GetHashCode();
          if (Status.Length != 0) hash ^= Status.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (RequestId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(RequestId);
          }
          if (ClientContextId.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(ClientContextId);
          }
          if (metrics_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(Metrics);
          }
          if (Signature.Length != 0) {
            output.WriteRawTag(34);
            output.WriteBytes(Signature);
          }
          warnings_.WriteTo(output, _repeated_warnings_codec);
          if (Status.Length != 0) {
            output.WriteRawTag(50);
            output.WriteString(Status);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (RequestId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(RequestId);
          }
          if (ClientContextId.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(ClientContextId);
          }
          if (metrics_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(Metrics);
          }
          if (Signature.Length != 0) {
            output.WriteRawTag(34);
            output.WriteBytes(Signature);
          }
          warnings_.WriteTo(ref output, _repeated_warnings_codec);
          if (Status.Length != 0) {
            output.WriteRawTag(50);
            output.WriteString(Status);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (RequestId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
          }
          if (ClientContextId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientContextId);
          }
          if (metrics_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Metrics);
          }
          if (Signature.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Signature);
          }
          size += warnings_.CalculateSize(_repeated_warnings_codec);
          if (Status.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Status);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(MetaData other) {
          if (other == null) {
            return;
          }
          if (other.RequestId.Length != 0) {
            RequestId = other.RequestId;
          }
          if (other.ClientContextId.Length != 0) {
            ClientContextId = other.ClientContextId;
          }
          if (other.metrics_ != null) {
            if (metrics_ == null) {
              Metrics = new global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.Metrics();
            }
            Metrics.MergeFrom(other.Metrics);
          }
          if (other.Signature.Length != 0) {
            Signature = other.Signature;
          }
          warnings_.Add(other.warnings_);
          if (other.Status.Length != 0) {
            Status = other.Status;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                RequestId = input.ReadString();
                break;
              }
              case 18: {
                ClientContextId = input.ReadString();
                break;
              }
              case 26: {
                if (metrics_ == null) {
                  Metrics = new global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.Metrics();
                }
                input.ReadMessage(Metrics);
                break;
              }
              case 34: {
                Signature = input.ReadBytes();
                break;
              }
              case 42: {
                warnings_.AddEntriesFrom(input, _repeated_warnings_codec);
                break;
              }
              case 50: {
                Status = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                RequestId = input.ReadString();
                break;
              }
              case 18: {
                ClientContextId = input.ReadString();
                break;
              }
              case 26: {
                if (metrics_ == null) {
                  Metrics = new global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.Metrics();
                }
                input.ReadMessage(Metrics);
                break;
              }
              case 34: {
                Signature = input.ReadBytes();
                break;
              }
              case 42: {
                warnings_.AddEntriesFrom(ref input, _repeated_warnings_codec);
                break;
              }
              case 50: {
                Status = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the MetaData message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
          public sealed partial class Warning : pb::IMessage<Warning>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<Warning> _parser = new pb::MessageParser<Warning>(() => new Warning());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<Warning> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Couchbase.Protostellar.Analytics.V1.AnalyticsQueryResponse.Types.MetaData.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Warning() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Warning(Warning other) : this() {
              code_ = other.code_;
              message_ = other.message_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Warning Clone() {
              return new Warning(this);
            }

            /// <summary>Field number for the "code" field.</summary>
            public const int CodeFieldNumber = 1;
            private uint code_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public uint Code {
              get { return code_; }
              set {
                code_ = value;
              }
            }

            /// <summary>Field number for the "message" field.</summary>
            public const int MessageFieldNumber = 2;
            private string message_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string Message {
              get { return message_; }
              set {
                message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as Warning);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(Warning other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Code != other.Code) return false;
              if (Message != other.Message) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (Code != 0) hash ^= Code.GetHashCode();
              if (Message.Length != 0) hash ^= Message.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (Code != 0) {
                output.WriteRawTag(8);
                output.WriteUInt32(Code);
              }
              if (Message.Length != 0) {
                output.WriteRawTag(18);
                output.WriteString(Message);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (Code != 0) {
                output.WriteRawTag(8);
                output.WriteUInt32(Code);
              }
              if (Message.Length != 0) {
                output.WriteRawTag(18);
                output.WriteString(Message);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (Code != 0) {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Code);
              }
              if (Message.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(Warning other) {
              if (other == null) {
                return;
              }
              if (other.Code != 0) {
                Code = other.Code;
              }
              if (other.Message.Length != 0) {
                Message = other.Message;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 8: {
                    Code = input.ReadUInt32();
                    break;
                  }
                  case 18: {
                    Message = input.ReadString();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 8: {
                    Code = input.ReadUInt32();
                    break;
                  }
                  case 18: {
                    Message = input.ReadString();
                    break;
                  }
                }
              }
            }
            #endif

          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
